#include <pebble.h>


  
static Window *s_main_window;

static PropertyAnimation *s_property_animation;

short displayed_hour_digit_1 = -1;
short displayed_hour_digit_2 = -1;
short displayed_minute_digit_1 = -1;
short displayed_minute_digit_2 = -1;
short new_hour_digit_1 = -1;
short new_hour_digit_2 = -1;
short new_minute_digit_1 = -1;
short new_minute_digit_2 = -1;

// There's only enough memory to load about 6 of 10 required images
// so we have to swap them in & out... (Ouch!)
//
// We have one "slot" per digit location on screen.
//
// Because layers can only have one parent we load a digit for each
// slot--even if the digit image is already in another slot.
//
// Slot on-screen layout:
//     0 1
//     2 3
#define TOTAL_IMAGE_SLOTS 4
#define NUMBER_OF_IMAGES 10
#define TRANSITION_MS 300
#define DIGIT_WIDTH  72
#define DIGIT_HEIGHT  84

// These images are 72 x 84 pixels (i.e. a quarter of the display),
// black and white with the digit character centered in the image.
// (As generated by the `fonttools/font2png.py` script.)
const int IMAGE_RESOURCE_IDS[NUMBER_OF_IMAGES] = {
  RESOURCE_ID_IMAGE_NUM_0, RESOURCE_ID_IMAGE_NUM_1, RESOURCE_ID_IMAGE_NUM_2,
  RESOURCE_ID_IMAGE_NUM_3, RESOURCE_ID_IMAGE_NUM_4, RESOURCE_ID_IMAGE_NUM_5,
  RESOURCE_ID_IMAGE_NUM_6, RESOURCE_ID_IMAGE_NUM_7, RESOURCE_ID_IMAGE_NUM_8,
  RESOURCE_ID_IMAGE_NUM_9
};

static GBitmap *s_images[TOTAL_IMAGE_SLOTS];
static BitmapLayer *s_image_layers[TOTAL_IMAGE_SLOTS];

#define EMPTY_SLOT -1

// The state is either "empty" or the digit of the image currently in
// the slot--which was going to be used to assist with de-duplication
// but we're not doing that due to the one parent-per-layer
// restriction mentioned above.
static int s_image_slot_state[TOTAL_IMAGE_SLOTS] = {EMPTY_SLOT, EMPTY_SLOT, EMPTY_SLOT, EMPTY_SLOT};


static void load_digit_image_into_slot(int slot_number, int digit_value) {
  /*
   * Loads the digit image from the application's resources and
   * displays it on-screen in the correct location.
   *
   * Each slot is a quarter of the screen.
   */

  if ((slot_number < 0) || (slot_number >= TOTAL_IMAGE_SLOTS)) {
    return;
  }

  if ((digit_value < 0) || (digit_value > 9)) {
    return;
  }

  if (s_image_slot_state[slot_number] != EMPTY_SLOT) {
    return;
  }

  s_image_slot_state[slot_number] = digit_value;
  s_images[slot_number] = gbitmap_create_with_resource(IMAGE_RESOURCE_IDS[digit_value]);
#ifdef PBL_PLATFORM_BASALT
  GRect bounds = gbitmap_get_bounds(s_images[slot_number]);
#else
  GRect bounds = s_images[slot_number]->bounds;
#endif
  BitmapLayer *bitmap_layer = bitmap_layer_create(GRect((slot_number % 2) * 72, (slot_number / 2) * 84, bounds.size.w, bounds.size.h));
  s_image_layers[slot_number] = bitmap_layer;
  bitmap_layer_set_bitmap(bitmap_layer, s_images[slot_number]);
  Layer *window_layer = window_get_root_layer(s_main_window);
  layer_add_child(window_layer, bitmap_layer_get_layer(bitmap_layer));
}



static void unload_digit_image_from_slot(int slot_number) {
  if (s_image_slot_state[slot_number] != EMPTY_SLOT) {
    layer_remove_from_parent(bitmap_layer_get_layer(s_image_layers[slot_number]));
    bitmap_layer_destroy(s_image_layers[slot_number]);
    gbitmap_destroy(s_images[slot_number]);
    s_image_slot_state[slot_number] = EMPTY_SLOT;
  }
}








static void show_hour2(){
  APP_LOG(APP_LOG_LEVEL_DEBUG, "show_hour2 now %d", new_hour_digit_2);

  //first destroy old image....
  unload_digit_image_from_slot(1);
  //create new image
  s_image_slot_state[1] = new_hour_digit_2; 
  s_images[1] = gbitmap_create_with_resource(IMAGE_RESOURCE_IDS[new_hour_digit_2]);
  //animate down
  #ifdef PBL_PLATFORM_BASALT
    GRect bounds = gbitmap_get_bounds(s_images[1]);
  #else
    GRect bounds = s_images[1]->bounds;
  #endif
  GRect from_frame = GRect(DIGIT_WIDTH*2, 0, bounds.size.w, bounds.size.h);
  GRect to_frame = GRect(DIGIT_WIDTH, 0, bounds.size.w, bounds.size.h);

  BitmapLayer *bitmap_layer = bitmap_layer_create(from_frame);
  s_image_layers[1] = bitmap_layer;
  bitmap_layer_set_bitmap(bitmap_layer, s_images[1]);
  Layer *window_layer = window_get_root_layer(s_main_window);
  layer_add_child(window_layer, bitmap_layer_get_layer(bitmap_layer));
   
  //animate
  s_property_animation = property_animation_create_layer_frame(bitmap_layer_get_layer(bitmap_layer), &from_frame, &to_frame);
  animation_set_duration((Animation*) s_property_animation, TRANSITION_MS);
//   animation_set_handlers((Animation*) s_property_animation, (AnimationHandlers) {
//     .stopped = (AnimationStoppedHandler) clear_minute1
//     }, NULL);
  animation_schedule((Animation*) s_property_animation);
}





 

static void clear_hour2(){

  if(new_hour_digit_2!=displayed_hour_digit_2){
    displayed_hour_digit_2=new_hour_digit_2;
//     this digit changed
    APP_LOG(APP_LOG_LEVEL_DEBUG, "clear_hour2, digit 2 changing from %d", displayed_hour_digit_2);
  #ifdef PBL_PLATFORM_BASALT
    GRect bounds = gbitmap_get_bounds(s_images[1]);
  #else
    GRect bounds = s_images[1]->bounds;
  #endif
  GRect from_frame = GRect(DIGIT_WIDTH, 0, bounds.size.w, bounds.size.h);
  GRect to_frame = GRect(DIGIT_HEIGHT*2, 0, bounds.size.w, bounds.size.h);
  if (s_image_slot_state[1] == EMPTY_SLOT) {
   load_digit_image_into_slot(1,new_hour_digit_2); 
  }
    //animate...
    s_property_animation = property_animation_create_layer_frame(bitmap_layer_get_layer(s_image_layers[1]), &from_frame, &to_frame);
    animation_set_duration((Animation*) s_property_animation, TRANSITION_MS);
    animation_set_handlers((Animation*) s_property_animation, (AnimationHandlers) {
      .stopped = (AnimationStoppedHandler) show_hour2
      }, NULL);
    animation_schedule((Animation*) s_property_animation);
 
  }else{
    APP_LOG(APP_LOG_LEVEL_DEBUG, "clear_hour2, digit 2 staying %d", displayed_hour_digit_2);

    //no change, check next digit...
  }
}

static void show_hour1(){
  APP_LOG(APP_LOG_LEVEL_DEBUG, "show_hour1 now %d", new_hour_digit_1);

  //first destroy old image....
  unload_digit_image_from_slot(0);
  //create new image
  s_image_slot_state[0] = new_hour_digit_1; 
  s_images[0] = gbitmap_create_with_resource(IMAGE_RESOURCE_IDS[new_hour_digit_1]);
  //animate down
  #ifdef PBL_PLATFORM_BASALT
    GRect bounds = gbitmap_get_bounds(s_images[0]);
  #else
    GRect bounds = s_images[0]->bounds;
  #endif
  GRect from_frame = GRect(0, 0-DIGIT_HEIGHT, bounds.size.w, bounds.size.h);
  GRect to_frame = GRect(0, 0, bounds.size.w, bounds.size.h);

  BitmapLayer *bitmap_layer = bitmap_layer_create(from_frame);
  s_image_layers[0] = bitmap_layer;
  bitmap_layer_set_bitmap(bitmap_layer, s_images[0]);
  Layer *window_layer = window_get_root_layer(s_main_window);
  layer_add_child(window_layer, bitmap_layer_get_layer(bitmap_layer));
   
  //animate
  s_property_animation = property_animation_create_layer_frame(bitmap_layer_get_layer(bitmap_layer), &from_frame, &to_frame);
  animation_set_duration((Animation*) s_property_animation, TRANSITION_MS);
  animation_set_handlers((Animation*) s_property_animation, (AnimationHandlers) {
    .stopped = (AnimationStoppedHandler) clear_hour2
    }, NULL);
  animation_schedule((Animation*) s_property_animation);
}


static void clear_hour1(){

  if(new_hour_digit_1!=displayed_hour_digit_1){
    displayed_hour_digit_1=new_hour_digit_1;
//     this digit changed
    APP_LOG(APP_LOG_LEVEL_DEBUG, "clear_hour1, digit 1 changing from %d", displayed_hour_digit_1);
  #ifdef PBL_PLATFORM_BASALT
    GRect bounds = gbitmap_get_bounds(s_images[0]);
  #else
    GRect bounds = s_images[0]->bounds;
  #endif
  GRect from_frame = GRect(0, 0, bounds.size.w, bounds.size.h);
  GRect to_frame = GRect(0-DIGIT_HEIGHT, 0, bounds.size.w, bounds.size.h);
  if (s_image_slot_state[0] == EMPTY_SLOT) {
   load_digit_image_into_slot(0,new_hour_digit_1); 
  }
    //animate...
    s_property_animation = property_animation_create_layer_frame(bitmap_layer_get_layer(s_image_layers[0]), &from_frame, &to_frame);
    animation_set_duration((Animation*) s_property_animation, TRANSITION_MS);
    animation_set_handlers((Animation*) s_property_animation, (AnimationHandlers) {
      .stopped = (AnimationStoppedHandler) show_hour1
      }, NULL);
    animation_schedule((Animation*) s_property_animation);
 
  }else{
    APP_LOG(APP_LOG_LEVEL_DEBUG, "clear_hour1, digit 1 staying %d", displayed_hour_digit_1);

    //no change, check next digit...
  }
}

  








static unsigned short get_display_hour(unsigned short hour) {
  if (clock_is_24h_style()) {
    return hour;
  }
  unsigned short display_hour = hour % 12;
  // Converts "0" to "12"
  return display_hour ? display_hour : 12;
}

 
static void update_now_digits(struct tm *tick_time){
  short hour = get_display_hour(tick_time->tm_hour);
  short minutes = tick_time->tm_sec;
  new_hour_digit_1 = hour / 10;
  new_hour_digit_2 = hour % 10;
  new_minute_digit_1 = minutes / 10;
  new_minute_digit_2 = minutes % 10;
}


/*
* This function sets the current time 
* digit values and then calls a method that will call others to make the digit changes.
*/
static void display_time(struct tm *tick_time) {
  //first set now digits...
  update_now_digits(tick_time);
  //for testing force new digit change everytime...
  new_hour_digit_1 = (displayed_hour_digit_1 + 1) % 10;
  new_hour_digit_2 = (displayed_hour_digit_2 + 1)  % 10;
  new_minute_digit_1 = (displayed_minute_digit_1 + 1) % 10;
  new_minute_digit_2 = (displayed_minute_digit_2 + 1)  % 10;
  
  
  clear_hour1();
  
//   display_value(get_display_hour(tick_time->tm_hour), 0, false);
//   display_value(tick_time->tm_min, 1, true);
//   display_value(tick_time->tm_sec, 1, true);
}



/*
* This is called by a system timer every minute change. It starts the display change.
*/
static void handle_minute_tick(struct tm *tick_time, TimeUnits units_changed) {
  int seconds = tick_time->tm_sec;
  if(seconds % 3 == 0){
     display_time(tick_time); 
  }
//   display_time(tick_time);
}



static void main_window_load(Window *window) {
  time_t now = time(NULL);
  struct tm *tick_time = localtime(&now);
  display_time(tick_time);

//   tick_timer_service_subscribe(MINUTE_UNIT, handle_minute_tick);
  tick_timer_service_subscribe(SECOND_UNIT, handle_minute_tick);
}



static void main_window_unload(Window *window) {
  for (int i = 0; i < TOTAL_IMAGE_SLOTS; i++) {
    unload_digit_image_from_slot(i);
  }
}



static void init() {
  s_main_window = window_create();
  window_set_background_color(s_main_window, GColorBlack);
  window_set_window_handlers(s_main_window, (WindowHandlers) {
    .load = main_window_load,
    .unload = main_window_unload,
  });
  window_stack_push(s_main_window, true);
}



static void deinit() {
  window_destroy(s_main_window);
}



int main(void) {
  init();
  app_event_loop();
  deinit();
}
