#include <pebble.h>


/*
 __  __                           _____ _
|  \/  | ___  _ __   __ _  ___   |_   _(_)_ __ ___   ___
| |\/| |/ _ \| '_ \ / _` |/ _ \    | | | | '_ ` _ \ / _ \
| |  | | (_) | | | | (_| | (_) |   | | | | | | | | |  __/
|_|  |_|\___/|_| |_|\__, |\___/    |_| |_|_| |_| |_|\___|
                    |___/
*/


/*
ref: http://www.newty.de/fpt/fpt.html#passPtr
*/

  
// There's only enough memory to load about 6 of 10 required images
// so we have to swap them in & out... (Ouch!)
//
// We have one "slot" per digit location on screen.
//
// Because layers can only have one parent we load a digit for each
// slot--even if the digit image is already in another slot.
//
// Slot on-screen layout:
//     0 1
//     2 3
#define TOTAL_IMAGE_SLOTS 4
#define NUMBER_OF_IMAGES 10
#define TRANSITION_MS_DEFAULT 2000
#define DIGIT_WIDTH  72
#define DIGIT_HEIGHT  84  
#define EMPTY_SLOT -1
#define TEST_DRIVER false
  
static Window *s_main_window;

static PropertyAnimation *s_property_animation;

short new_hour_digit_0 = -1;
short new_hour_digit_1 = -1;
short new_minute_digit_0 = -1;
short new_minute_digit_1 = -1;
int transition_ms = TRANSITION_MS_DEFAULT;
bool animate_all_digits = false;
bool first_display_done = false;



// These images are 72 x 84 pixels (i.e. a quarter of the display),
// black and white with the digit character centered in the image.
// (As generated by the `fonttools/font2png.py` script.)
const int IMAGE_RESOURCE_IDS[NUMBER_OF_IMAGES] = {
  RESOURCE_ID_IMAGE_NUM_0, RESOURCE_ID_IMAGE_NUM_1, RESOURCE_ID_IMAGE_NUM_2,
  RESOURCE_ID_IMAGE_NUM_3, RESOURCE_ID_IMAGE_NUM_4, RESOURCE_ID_IMAGE_NUM_5,
  RESOURCE_ID_IMAGE_NUM_6, RESOURCE_ID_IMAGE_NUM_7, RESOURCE_ID_IMAGE_NUM_8,
  RESOURCE_ID_IMAGE_NUM_9
};

static GBitmap *s_images[TOTAL_IMAGE_SLOTS];
static BitmapLayer *s_image_layers[TOTAL_IMAGE_SLOTS];


// The state is either "empty" or the digit of the image currently in
// the slot--which was going to be used to assist with de-duplication
// but we're not doing that due to the one parent-per-layer
// restriction mentioned above.
static int s_image_slot_state[TOTAL_IMAGE_SLOTS] = {EMPTY_SLOT, EMPTY_SLOT, EMPTY_SLOT, EMPTY_SLOT};

//Add some prototypes because C is lame...
static unsigned short get_display_hour(unsigned short hour);
static void clear_hour0();

static void load_digit_image_into_slot(int slot_number, int digit_value, void *next_call ) {
  APP_LOG(APP_LOG_LEVEL_DEBUG, "load_digit_image_into_slot, loading slot %d", slot_number);

  /*
   * Loads the digit image from the application's resources and
   * displays it on-screen in the correct location.
   *
   * Each slot is a quarter of the screen.
   */

  
    //destroy old before putting in new
  layer_remove_from_parent(bitmap_layer_get_layer(s_image_layers[slot_number]));
  bitmap_layer_destroy(s_image_layers[slot_number]);
  gbitmap_destroy(s_images[slot_number]);
  
  
  s_image_slot_state[slot_number] = digit_value;
  s_images[slot_number] = gbitmap_create_with_resource(IMAGE_RESOURCE_IDS[digit_value]);
  #ifdef PBL_PLATFORM_BASALT
    GRect bounds = gbitmap_get_bounds(s_images[slot_number]);
  #else
    GRect bounds = s_images[slot_number]->bounds;
  #endif
  
  //defaults are for slot0
  //slide in vertically
  int startx,starty,endx,endy;
  startx = 0 ;
  starty = 0 - DIGIT_HEIGHT;
  endx = 0;
  endy = 0;
  if(slot_number==1){
    startx = DIGIT_WIDTH;
    endx = DIGIT_WIDTH;
  } else if(slot_number==2){
    starty = DIGIT_HEIGHT * 2;
    endy= DIGIT_HEIGHT;
  }  else if(slot_number==3){
    startx = DIGIT_WIDTH;
    endx = DIGIT_WIDTH;
    starty = DIGIT_HEIGHT * 2;
    endy= DIGIT_HEIGHT;
  }
  

  //animated...
  GRect from_frame = GRect(startx, starty, bounds.size.w, bounds.size.h);
  GRect to_frame = GRect(endx, endy, bounds.size.w, bounds.size.h);

  BitmapLayer *bitmap_layer = bitmap_layer_create(from_frame);
  s_image_layers[slot_number] = bitmap_layer;
  bitmap_layer_set_bitmap(bitmap_layer, s_images[slot_number]);
  Layer *window_layer = window_get_root_layer(s_main_window);
  layer_add_child(window_layer, bitmap_layer_get_layer(bitmap_layer));

  #ifdef PBL_PLATFORM_APLITE
    // Free the animation
    property_animation_destroy(s_property_animation);
  #endif
  
  
  // Create the animation
  s_property_animation = property_animation_create_layer_frame(bitmap_layer_get_layer(bitmap_layer), &from_frame, &to_frame);
  //set duration
  animation_set_duration((Animation*) s_property_animation, transition_ms);
  if(next_call!=NULL){
    animation_set_handlers((Animation*) s_property_animation, (AnimationHandlers) {
      .stopped = (AnimationStoppedHandler) next_call
    }, NULL);
  }
  // Schedule to occur ASAP with default settings
  animation_schedule((Animation*) s_property_animation);

  
}




static void unload_digit_image_from_slot(int slot_number,void (*next_call)()) {
  APP_LOG(APP_LOG_LEVEL_DEBUG, "unload_digit_image_from_slot: unloading slot %d", slot_number);

  
  if( s_image_slot_state[slot_number] == EMPTY_SLOT){
    //nothing to unload...
    APP_LOG(APP_LOG_LEVEL_DEBUG, "unload_digit_image_from_slot: slot #%d is empty", slot_number);
    if(next_call!=NULL){
      (*next_call)(); 
    }
    return;
  } 
  //slide out horizontially...
  int startx,starty,endx,endy;
//   APP_LOG(APP_LOG_LEVEL_DEBUG, "unload_digit_image_from_slot: %s", "still alive -2");
  startx = 0 ;
  starty = 0 ;
  endx = 0-DIGIT_HEIGHT;
  endy = 0;
  if(slot_number==1){
    startx = DIGIT_WIDTH;
    endx = DIGIT_WIDTH*2;
  } else if(slot_number==2){
    starty = DIGIT_HEIGHT;
    endy= DIGIT_HEIGHT;
  }  else if(slot_number==3){
    startx = DIGIT_WIDTH;
    starty = DIGIT_HEIGHT ;
    endx = DIGIT_WIDTH*2;
    endy= DIGIT_HEIGHT;
  }
  #ifdef PBL_PLATFORM_BASALT
    GRect bounds = gbitmap_get_bounds(s_images[slot_number]);
  #else
//     APP_LOG(APP_LOG_LEVEL_DEBUG, "unload_digit_image_from_slot: %s", "still alive -1");
    GRect bounds = s_images[slot_number]->bounds;
//   APP_LOG(APP_LOG_LEVEL_DEBUG, "unload_digit_image_from_slot: %s", "still alive 0");
  #endif

  GRect from_frame = GRect(startx, starty, bounds.size.w, bounds.size.h);
  GRect to_frame = GRect(endx, endy, bounds.size.w, bounds.size.h);
  if (s_image_slot_state[slot_number] != EMPTY_SLOT) {
    #ifdef PBL_PLATFORM_APLITE
      // Free the animation
      property_animation_destroy(s_property_animation);
    #endif
//          APP_LOG(APP_LOG_LEVEL_DEBUG, "unload_digit_image_from_slot: %s", "still alive 1");

    //animate...
    s_property_animation = property_animation_create_layer_frame(bitmap_layer_get_layer(s_image_layers[slot_number]), &from_frame, &to_frame);
    //set duration
    animation_set_duration((Animation*) s_property_animation, transition_ms);
//       APP_LOG(APP_LOG_LEVEL_DEBUG, "unload_digit_image_from_slot: %s", "still alive 2");

    if(next_call!=NULL){
      APP_LOG(APP_LOG_LEVEL_DEBUG, "unload_digit_image_from_slot, callback handler will be called %d",1);
      animation_set_handlers((Animation*) s_property_animation, (AnimationHandlers) {
        .stopped = (AnimationStoppedHandler) next_call
      }, NULL);
    }else{
//       APP_LOG(APP_LOG_LEVEL_DEBUG, "unload_digit_image_from_slot, callback handler is null %d",1);

    }
    animation_schedule((Animation*) s_property_animation);
//       APP_LOG(APP_LOG_LEVEL_DEBUG, "unload_digit_image_from_slot: %s", "still alive 3");

  } else {
    //     empty slot, do next call...
    if(next_call!=NULL){
      (*next_call)(); 
    }
  }
  
  APP_LOG(APP_LOG_LEVEL_DEBUG, "unload_digit_image_from_slot: %s", "done");

}


/*
* This function sets the current time 
* digit values and then calls a method that will call others to make the digit changes.
*/
static void display_time(struct tm *tick_time) {
  APP_LOG(APP_LOG_LEVEL_DEBUG, "\n===\ndisplay_time: called at %d:%d:%d", tick_time->tm_hour,tick_time->tm_min,tick_time->tm_sec);

  //first set now digits...
  short hour = get_display_hour(tick_time->tm_hour);
  short minutes = tick_time->tm_min;
  new_hour_digit_0 = hour / 10;
  new_hour_digit_1 = hour % 10;
  new_minute_digit_0 = minutes / 10;
  new_minute_digit_1 = minutes % 10;
  //for testing force new digit change everytime...
  #if TEST_DRIVER
//    new_hour_digit_0 = (s_image_slot_state[0] + 1) % 10;
//    new_hour_digit_1 = (new_hour_digit_0 + 1)  % 10;
//    new_minute_digit_0 = (new_hour_digit_1 + 1) % 10;
//    new_minute_digit_1 = (new_minute_digit_0 + 1)  % 10;
  #endif
  //adjust transtion times, more digits changing shorten transition...
  short digit_change_count =1;
  if(new_hour_digit_0!=s_image_slot_state[0]) digit_change_count++;
  if(new_hour_digit_1!=s_image_slot_state[1]) digit_change_count++;
  if(new_minute_digit_0!=s_image_slot_state[2]) digit_change_count++;
  if(animate_all_digits) digit_change_count=4;
  //digit_change_count*2 to account for transition for remove and add of each digit
  transition_ms = TRANSITION_MS_DEFAULT / (digit_change_count*2);
  APP_LOG(APP_LOG_LEVEL_DEBUG, "display_time: digits changed=%d, transition_time=%d, new time=%d%d:%d%d", 
          digit_change_count,transition_ms,new_hour_digit_0,new_hour_digit_1,new_minute_digit_0,new_minute_digit_1);

  //Start the chain of updates to digits, starting with left hour digit
   clear_hour0();
}



/*
* This is called by a system timer every minute change. It starts the display change.
*/
static void handle_minute_tick(struct tm *tick_time, TimeUnits units_changed) {
  #if TEST_DRIVER
    APP_LOG(APP_LOG_LEVEL_DEBUG,"%s", "\n\nhandle_minute_tick: calling display_time as TEST_DRIVER");
   if(tick_time->tm_sec % 5 == 0)
     display_time(tick_time); 
  #else
    APP_LOG(APP_LOG_LEVEL_DEBUG,"%s", "\n\nhandle_minute_tick: calling display_time as production call");
    display_time(tick_time); 
  #endif
}


static void display_time_postprocess(){
  if( !first_display_done){
  #if TEST_DRIVER
    APP_LOG(APP_LOG_LEVEL_DEBUG,"%s", "display_time_postprocess, called TEST_DRIVER with 1sec timer");
    tick_timer_service_subscribe(SECOND_UNIT, handle_minute_tick);  
  #else
    APP_LOG(APP_LOG_LEVEL_DEBUG,"%s", "display_time_postprocess, production mode with 1min timer");
    tick_timer_service_subscribe(MINUTE_UNIT, handle_minute_tick);
  #endif
    first_display_done=true;
  }else{
    
  }
  
}


static void show_minute1(){
    //this digit changed   
    APP_LOG(APP_LOG_LEVEL_DEBUG, "show_minute1, minute digit 1 changing from %d to %d", s_image_slot_state[3],new_minute_digit_1);
    load_digit_image_into_slot(3,new_minute_digit_1,display_time_postprocess); 
}

static void clear_minute1(){
  if(animate_all_digits || new_minute_digit_1!=s_image_slot_state[3]){
    APP_LOG(APP_LOG_LEVEL_DEBUG, "clear_minute1: minute digit 1 changing %d", s_image_slot_state[3]);
    unload_digit_image_from_slot(3,show_minute1);  
  }else{
    APP_LOG(APP_LOG_LEVEL_DEBUG, "clear_minute1: minute digit 1 staying %d", s_image_slot_state[3]);
    //no change, check next digit...
  }    
}





static void show_minute0(){
    //this digit changed   
    APP_LOG(APP_LOG_LEVEL_DEBUG, "show_minute0, minute digit 0 changing from %d to %d", s_image_slot_state[2],new_minute_digit_0);
    load_digit_image_into_slot(2,new_minute_digit_0,clear_minute1); 
}




static void clear_minute0(){
  if(animate_all_digits || new_minute_digit_0!=s_image_slot_state[2]){
    APP_LOG(APP_LOG_LEVEL_DEBUG, "clear_minute0, minute digit 0 changing %d", s_image_slot_state[2]);
    unload_digit_image_from_slot(2,show_minute0);  
  }else{
    APP_LOG(APP_LOG_LEVEL_DEBUG, "clear_minute0, minute digit 0 staying %d", s_image_slot_state[2]);
    clear_minute1();
  }    
}







static void show_hour1(){
    //this digit changed   
    APP_LOG(APP_LOG_LEVEL_DEBUG, "show_hour1, hour digit 1 changing from %d to %d", s_image_slot_state[1],new_hour_digit_1);
    load_digit_image_into_slot(1,new_hour_digit_1,clear_minute0); 
}




static void clear_hour1(){
  if(animate_all_digits || new_hour_digit_1!=s_image_slot_state[1]){
    APP_LOG(APP_LOG_LEVEL_DEBUG, "clear_hour1: hour digit 1 changing %d", s_image_slot_state[1]);
    unload_digit_image_from_slot(1,show_hour1);  
  }else{
    APP_LOG(APP_LOG_LEVEL_DEBUG, "clear_hour1: hour digit 1 staying %d", s_image_slot_state[1]);
    //no change, check next digit...
    clear_minute0();
  }  
}







static void show_hour0(){
    //this digit changed
    APP_LOG(APP_LOG_LEVEL_DEBUG, "show_hour0, hour digit 0 changing from %d to %d", s_image_slot_state[0], new_hour_digit_0);
    load_digit_image_into_slot(0,new_hour_digit_0,clear_hour1); 
}


static void clear_hour0(){
  if(animate_all_digits || new_hour_digit_0!=s_image_slot_state[0]){
    APP_LOG(APP_LOG_LEVEL_DEBUG, "clear_hour0: hour digit 0 changing %d", s_image_slot_state[0]);
    unload_digit_image_from_slot(0,show_hour0);
  }else{
    APP_LOG(APP_LOG_LEVEL_DEBUG, "clear_hour0: hour digit 0 staying %d", s_image_slot_state[0]);
    //no change, check next digit...
    clear_hour1();
  }
}







static unsigned short get_display_hour(unsigned short hour) {
  if (clock_is_24h_style()) {
    return hour;
  }
  unsigned short display_hour = hour % 12;
  // Converts "0" to "12"
  return display_hour ? display_hour : 12;
}






static void main_window_load(Window *window) {
  time_t now = time(NULL);
  struct tm *tick_time = localtime(&now);
  display_time(tick_time);
    APP_LOG(APP_LOG_LEVEL_DEBUG, "main_window_load: slot values= %d,%d,%d,%d",s_image_slot_state[0],s_image_slot_state[1],s_image_slot_state[2],s_image_slot_state[3] );
}



static void main_window_unload(Window *window) {
  APP_LOG(APP_LOG_LEVEL_DEBUG, "main_window_unload: %s", "unloading");
  for (int i = 0; i < TOTAL_IMAGE_SLOTS; i++) {
    unload_digit_image_from_slot(i,NULL);
  }
}



static void init() {
  s_main_window = window_create();
  window_set_background_color(s_main_window, GColorBlack);
  window_set_window_handlers(s_main_window, (WindowHandlers) {
    .load = main_window_load,
    .unload = main_window_unload,
  });
  window_stack_push(s_main_window, true);
}



static void deinit() {
  window_destroy(s_main_window);
}



int main(void) {
  init();
  app_event_loop();
  deinit();
}
